server:
  port: 9090

mybatis:
  mapper-locations: mapper/UserMapper.xml
  type-aliases-package: com.domcj.seccache.seccache.entity
#  configuration:
#    cache-enabled: true

spring:
  datasource:
      url: jdbc:mysql://localhost:3306/chenjian
      username: root
      password: chenjian
      driver-class-name: com.mysql.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource
  redis:
    host: localhost
    port: 6379
    database: 0
    password:
